# Generated by Django 2.0.3 on 2018-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatedgamesearch', '0002_auto_20180325_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgggame',
            old_name='bgg_game',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bgguser',
            old_name='bgg_user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usergameranking',
            old_name='bgg_game',
            new_name='game_name',
        ),
        migrations.RenameField(
            model_name='usergameranking',
            old_name='bgg_user',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='Rank',
        ),
        migrations.AddField(
            model_name='rank',
            name='rank',
            field=models.FloatField(default=9, max_length=10),
        ),
    ]
