# Generated by Django 2.0.3 on 2018-03-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatedgamesearch', '0003_auto_20180326_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergameranking',
            name='rank',
        ),
        migrations.AddField(
            model_name='usergameranking',
            name='rating',
            field=models.FloatField(default=9, max_length=10),
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
